"""adding small fields

Revision ID: 8fac9d046a90
Revises: 29aa7ca63e57
Create Date: 2023-11-27 15:52:55.837437

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8fac9d046a90"
down_revision: Union[str, None] = "29aa7ca63e57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("clubs", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.add_column("users", sa.Column("supabase_id", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "supabase_id")
    op.alter_column("clubs", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
