"""new friends table

Revision ID: 8d14cc7d3242
Revises: fd7319d26a1d
Create Date: 2023-11-28 21:04:29.906722

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d14cc7d3242"
down_revision: Union[str, None] = "fd7319d26a1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friends",
        sa.Column("requesting_guest_id", sa.Integer(), nullable=False),
        sa.Column("addressee_guest_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["addressee_guest_id"],
            ["guests.id"],
            name=op.f("fk_friends_addressee_guest_id_guests"),
        ),
        sa.ForeignKeyConstraint(
            ["requesting_guest_id"],
            ["guests.id"],
            name=op.f("fk_friends_requesting_guest_id_guests"),
        ),
        sa.PrimaryKeyConstraint(
            "requesting_guest_id",
            "addressee_guest_id",
            name=op.f("pk_friends"),
        ),
        sa.UniqueConstraint(
            "requesting_guest_id",
            "addressee_guest_id",
            name="unique_friendship",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("friends")
    # ### end Alembic commands ###
