"""creating new tables table

Revision ID: 29aa7ca63e57
Revises: 220202f601e2
Create Date: 2023-11-27 15:07:54.618408

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29aa7ca63e57"
down_revision: Union[str, None] = "220202f601e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tables",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("num_seats", sa.Integer(), nullable=False),
        sa.Column("price_in_usd_cents", sa.Integer(), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
            name=op.f("fk_tables_club_id_clubs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tables")),
    )
    op.create_table(
        "tier_to_num_tables_mappings",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("num_tables", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
            name=op.f("fk_tier_to_num_tables_mappings_club_id_clubs"),
        ),
        sa.PrimaryKeyConstraint(
            "club_id",
            "tier",
            name=op.f("pk_tier_to_num_tables_mappings"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tier_to_num_tables_mappings")
    op.drop_table("tables")
    # ### end Alembic commands ###
