"""additional features + bookings

Revision ID: fd7319d26a1d
Revises: 3ff8b6e2fc0c
Create Date: 2023-11-28 01:24:54.642422

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fd7319d26a1d"
down_revision: Union[str, None] = "3ff8b6e2fc0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guest_id", sa.Integer(), nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=False),
        sa.Column("booking_datetime", sa.DateTime(), nullable=False),
        sa.Column("num_guests", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["guests.id"],
            name=op.f("fk_bookings_guest_id_guests"),
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["tables.id"],
            name=op.f("fk_bookings_table_id_tables"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
    )
    op.drop_table("tier_to_num_tables_mappings")
    op.add_column("clubs", sa.Column("pricing_tier", sa.Integer(), nullable=True))
    op.add_column("clubs", sa.Column("opening_time", sa.Time(), nullable=True))
    op.add_column("clubs", sa.Column("closing_time", sa.Time(), nullable=True))
    op.add_column("clubs", sa.Column("banner_image_url", sa.String(), nullable=True))
    op.add_column(
        "tables",
        sa.Column("max_num_tables", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tables", "max_num_tables")
    op.drop_column("clubs", "banner_image_url")
    op.drop_column("clubs", "closing_time")
    op.drop_column("clubs", "opening_time")
    op.drop_column("clubs", "pricing_tier")
    op.create_table(
        "tier_to_num_tables_mappings",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("club_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("tier", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("num_tables", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
            name="fk_tier_to_num_tables_mappings_club_id_clubs",
        ),
        sa.PrimaryKeyConstraint(
            "club_id",
            "tier",
            name="pk_tier_to_num_tables_mappings",
        ),
    )
    op.drop_table("bookings")
    # ### end Alembic commands ###
