# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-ast  # simply checks whether the files parse as valid python.
  - id: debug-statements  # checks for debugger imports and py37+ `breakpoint()` calls in python source.
  - id: no-commit-to-branch  # don't commit to branch
  - id: trailing-whitespace  # trims trailing whitespace.
  - id: end-of-file-fixer  # ensures that a file is either empty, or ends with one newline.
  - id: requirements-txt-fixer  # sorts entries in requirements.txt.
  - id: detect-private-key  # detects the presence of private keys.
  - id: check-merge-conflict  # checks for files that contain merge conflict strings.

# - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
#   rev: v2.1.0
#   hooks:
#   - id: pretty-format-yaml
#     args:
#     - --autofix
#     - --preserve-quotes
#     - --indent=2

# - repo: https://github.com/astral-sh/ruff-pre-commit
#   # Ruff version.
#   rev: v0.0.286
#   hooks:
#   - id: ruff
#     name: ruff linting
#     args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.1.0
  hooks:
  - id: add-trailing-comma

- repo: local
  hooks:
  - id: autoflake
    name: autoflake
    entry: autoflake
    language: system
    types: [python]
    args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

  - id: isort
    name: isort
    entry: isort
    language: system
    types: [python]
    args: ["--profile", "black"]

  - id: black
    name: Format with Black
    entry: black
    language: system
    types: [python]
